#!/bin/bash

mount_cgroup() {
  if ! mount | grep -q "cgroup"; then
    echo "Mounting cgroup filesystem..."
    mkdir -p /sys/fs/cgroup
    mount -t cgroup2 none /sys/fs/cgroup
  fi
}

start() {
  mount_cgroup

  if [[ -z "$(pidof dockerd)" ]]; then
    if command -v dockerd &>/dev/null; then
      nohup dockerd >/dev/null 2>&1 &
    else
      /userdata/system/batocera-containers/batocera-containers
    fi
  else
    containers=$(docker ps -q)
    if [[ -n "$containers" ]]; then
      docker unpause $containers
    fi
  fi
}

restart() {
  pkill -f batocera-containers
  /userdata/system/batocera-containers/batocera-containers
}

stop() {
  containers=$(docker ps -q)
  if [[ -n "$containers" ]]; then
    docker pause $containers
  fi
}

case "$1" in
  start)
    start &
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
